version:      "30-Sep-2022"
copyright:    "2022"
author:       "alvinxrw2002"
name:         "Alvin Xavier Rakha Wardhana"
title:        "OS222: Operating Systems 2022-2"
githublink:   "https://github.com/alvinxrw2002/os222"
myloglink:    "/TXT/mylog.txt"
mypublickey:  "/TXT/mypubkey.txt"
myupdatelink: "/TXT/myupdate.txt"
tarballlink:  "https://os.vlsm.org/Log/alvinxrw2002.tar.bz2.txt"
encoding:     UTF-8
markdown:     kramdown
input:        GFM
hard_wrap:    false
github:       [metadata]
